# Generated by Django 2.2.7 on 2019-12-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_name',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_password',
            new_name='c_pw',
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
