# Generated by Django 2.2.7 on 2019-12-03 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191203_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='c_pw',
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
