# Generated by Django 2.2.7 on 2019-12-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20191203_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='c_id',
        ),
    ]
