# Generated by Django 2.2.7 on 2019-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20191203_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='c_gender',
        ),
        migrations.AddField(
            model_name='customer',
            name='c_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='c_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
