export const TimeSet = [
    {
        index: 1,
        start: '08:00',
        end: '09:53',
        name: '겨울왕국2',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 2,
        start: '09:20',
        end: '11:13',
        name: '겨울왕국2',
        theater: '강남',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 3,
        start: '10:15',
        end: '12:08',
        name: '겨울왕국2',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 4,
        start: '11:30',
        end: '13:23',
        name: '겨울왕국2',
        theater: '강남',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 5,
        start: '12:30',
        end: '14:23',
        name: '겨울왕국2',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 6,
        start: '13:25',
        end: '15:18',
        name: '겨울왕국2',
        theater: '강남',
        theaternum: 4,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 7,
        start: '09:40',
        end: '11:33',
        name: '겨울왕국2',
        theater: '강남대로',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 8,
        start: '11:55',
        end: '13:48',
        name: '겨울왕국2',
        theater: '강남대로',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 9,
        start: '16:45',
        end: '18:38',
        name: '겨울왕국2',
        theater: '강남대로',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 10,
        start: '08:00',
        end: '10:42',
        name: '포드 V 페라리',
        theater: '강남',
        theaternum: 6,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 11,
        start: '11:00',
        end: '13:42',
        name: '포드 V 페라리',
        theater: '강남',
        theaternum: 6,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 12,
        start: '12:40',
        end: '15:22',
        name: '포드 V 페라리',
        theater: '강동',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 13,
        start: '12:45',
        end: '15:27',
        name: '포드 V 페라리',
        theater: '군자',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 13,
        start: '17:55',
        end: '20:37',
        name: '포드 V 페라리',
        theater: '군자',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 14,
        start: '19:00',
        end: '21:40',
        name: '[Live] 2020 빈 필하모닉 신년음악회',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 15,
        start: '08:00',
        end: '09:52',
        name: '시동',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 16,
        start: '12:30',
        end: '14:22',
        name: '시동',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 17,
        start: '19:15',
        end: '21:07',
        name: '시동',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 18,
        start: '08:00',
        end: '21:40',
        name: '쥬만지: 넥스트 레벨',
        theater: '강남',
        theaternum: 7,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 19,
        start: '10:10',
        end: '12:23',
        name: '쥬만지: 넥스트 레벨',
        theater: '군자',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 20,
        start: '12:55',
        end: '15:08',
        name: '쥬만지: 넥스트 레벨',
        theater: '강동',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 21,
        start: '19:40',
        end: '21:53',
        name: '쥬만지: 넥스트 레벨',
        theater: '강남대로',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 22,
        start: '10:00',
        end: '12:20',
        name: '나이브스 아웃',
        theater: '군자',
        theaternum: 7,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 23,
        start: '13:45',
        end: '16:05',
        name: '나이브스 아웃',
        theater: '강동',
        theaternum: 9,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 24,
        start: '17:00',
        end: '19:20',
        name: '나이브스 아웃',
        theater: '강남대로',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 25,
        start: '09:40',
        end: '11:34',
        name: '감쪽같은 그녀',
        theater: '군자',
        theaternum: 4,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 26,
        start: '11:50',
        end: '13:44',
        name: '감쪽같은 그녀',
        theater: '강동',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 27,
        start: '16:15',
        end: '18:09',
        name: '감쪽같은 그녀',
        theater: '강동',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 28,
        start: '10:10',
        end: '12:03',
        name: '라스트 크리스마스',
        theater: '강동',
        theaternum: 10,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 29,
        start: '12:25',
        end: '14:18',
        name: '라스트 크리스마스',
        theater: '강남대로',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 30,
        start: '14:45',
        end: '16:38',
        name: '라스트 크리스마스',
        theater: '강동',
        theaternum: 10,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 31,
        start: '17:00',
        end: '20:40',
        name: '러브라이브! 니지가사키 학원 스쿨 아이돌 동호회 Frist Live',
        theater: '강남',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 32,
        start: '14:40',
        end: '17:13',
        name: '[뮤지컬] 웃는 남자',
        theater: '강남',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 33,
        start: '08:10',
        end: '09:57',
        name: '아내를 죽였다',
        theater: '강남',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 34,
        start: '08:50',
        end: '11:03',
        name: '쥬만지: 넥스트 레벨',
        theater: '수원',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 35,
        start: '10:30',
        end: '12:43',
        name: '쥬만지: 넥스트 레벨',
        theater: '용인',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 36,
        start: '10:55',
        end: '13:08',
        name: '쥬만지: 넥스트 레벨',
        theater: '동대문',
        theaternum: 8,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 37,
        start: '13:30',
        end: '15:43',
        name: '쥬만지: 넥스트 레벨',
        theater: '동대문',
        theaternum: 8,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 38,
        start: '15:40',
        end: '17:53',
        name: '쥬만지: 넥스트 레벨',
        theater: '용인',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 39,
        start: '16:35',
        end: '18:48',
        name: '쥬만지: 넥스트 레벨',
        theater: '수원',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 40,
        start: '18:40',
        end: '20:53',
        name: '쥬만지: 넥스트 레벨',
        theater: '안산',
        theaternum: 1,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 41,
        start: '08:55',
        end: '10:49',
        name: '감쪽같은 그녀',
        theater: '수원',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 42,
        start: '11:05',
        end: '12:54',
        name: '감쪽같은 그녀',
        theater: '안산',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 43,
        start: '15:05',
        end: '16:54',
        name: '감쪽같은 그녀',
        theater: '안산',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 44,
        start: '19:05',
        end: '20:54',
        name: '감쪽같은 그녀',
        theater: '안산',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 45,
        start: '09:00',
        end: '11:42',
        name: '포드 V 페라리',
        theater: '동대문',
        theaternum: 4,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 46,
        start: '12:30',
        end: '15:07',
        name: '포드 V 페라리',
        theater: '안산',
        theaternum: 6,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 45,
        start: '15:15',
        end: '17:57',
        name: '포드 V 페라리',
        theater: '동대문',
        theaternum: 4,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 46,
        start: '17:40',
        end: '20:17',
        name: '포드 V 페라리',
        theater: '안산',
        theaternum: 6,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 47,
        start: '09:00',
        end: '10:42',
        name: '아내를 죽였다',
        theater: '안산',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 48,
        start: '09:50',
        end: '11:37',
        name: '아내를 죽였다',
        theater: '용인',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 49,
        start: '12:35',
        end: '14:17',
        name: '아내를 죽였다',
        theater: '안산',
        theaternum: 2,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 50,
        start: '16:15',
        end: '18:02',
        name: '아내를 죽였다',
        theater: '수원',
        theaternum: 4,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 51,
        start: '17:55',
        end: '19:42',
        name: '아내를 죽였다',
        theater: '동대문',
        theaternum: 6,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 52,
        start: '08:55',
        end: '10:49',
        name: '감쪽같은 그녀',
        theater: '수원',
        theaternum: 5,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
    {
        index: 52,
        start: '11:05',
        end: '12:54',
        name: '감쪽같은 그녀',
        theater: '안산중앙',
        theaternum: 3,
        nowseat: 100,
        maxseat: 100,
        Seat: []
    },
];