# Generated by Django 2.2.7 on 2019-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_title',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
    ]
