# Generated by Django 2.2.7 on 2019-12-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_schedule_movie_theater_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_col',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_row',
        ),
        migrations.AddField(
            model_name='seat',
            name='st_col',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='st_row',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
