# Generated by Django 2.2.7 on 2019-12-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20191209_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='st_col',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='st_row',
            field=models.CharField(max_length=100),
        ),
    ]
