# Generated by Django 2.2.7 on 2019-12-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20191210_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_theater',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie_theater',
            name='mv_location',
        ),
        migrations.AddField(
            model_name='movie_theater',
            name='mt_index',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
