# Generated by Django 2.2.7 on 2019-12-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20191210_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_schedule',
            name='id',
        ),
        migrations.AddField(
            model_name='movie_schedule',
            name='ms_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie_schedule',
            name='ms_index',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movie_schedule',
            name='ms_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
