# Generated by Django 2.2.7 on 2019-12-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20191210_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_schedule',
            name='date_time',
        ),
    ]
