# Generated by Django 2.2.7 on 2019-12-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_schedule_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='st_booking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
