# Generated by Django 2.2.7 on 2019-12-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_seat_st_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='st_booking',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
