# Generated by Django 2.2.7 on 2019-12-10 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20191210_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_schedule',
            name='ms_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie_theater'),
        ),
    ]
