# Generated by Django 2.2.7 on 2019-12-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20191210_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='st_booking',
        ),
    ]
