# Generated by Django 2.2.7 on 2019-12-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_seat_st_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mv_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
