# Generated by Django 2.2.7 on 2019-12-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_auto_20191210_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mv_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
