# Generated by Django 2.2.7 on 2019-12-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_movie_mv_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('st_col', 'st_row')},
        ),
    ]
