# Generated by Django 2.2.7 on 2019-12-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_movie_theater_mt_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_theater',
            name='mt_seat',
        ),
        migrations.AddField(
            model_name='movie_theater',
            name='mt_seat',
            field=models.ManyToManyField(to='movie.Seat'),
        ),
    ]
