# Generated by Django 2.2.7 on 2019-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_auto_20191210_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_col', models.IntegerField(default=0)),
                ('st_row', models.IntegerField(default=0)),
                ('st_booking', models.CharField(default='ava', max_length=100)),
            ],
            options={
                'unique_together': {('st_col', 'st_row')},
            },
        ),
    ]
