# Generated by Django 2.2.7 on 2019-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_seat1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_theater1',
            fields=[
                ('mt_index', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('mt_region', models.CharField(blank=True, max_length=200, null=True)),
                ('mt_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mt_seat', models.ManyToManyField(to='movie.Seat1')),
            ],
        ),
    ]
