# Generated by Django 2.2.7 on 2019-12-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_movie_schedule1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='st_col',
            new_name='Col',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
