# Generated by Django 2.2.7 on 2019-12-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_auto_20191211_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='st_row',
            new_name='Row',
        ),
    ]
