# Generated by Django 2.2.7 on 2019-12-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_auto_20191211_0915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('Col', 'Row')},
        ),
    ]
