# Generated by Django 2.2.7 on 2019-12-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_auto_20191211_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat1',
            old_name='st_col',
            new_name='Col',
        ),
        migrations.AlterUniqueTogether(
            name='seat1',
            unique_together=set(),
        ),
    ]
